# Generated by Django 5.2.6 on 2025-09-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car_DB',
            fields=[
                ('car_company', models.CharField(max_length=20)),
                ('car_modelno', models.IntegerField(primary_key=True, serialize=False)),
                ('car_version', models.FloatField()),
                ('car_color', models.CharField(max_length=15)),
                ('car_type', models.CharField(max_length=15)),
            ],
        ),
    ]
